version: '3.2'

secrets:
  logstashconf:
    file: ./logstash.conf

services:

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.Elasticsearch
    image: cycloneproject/logging-elasticsearch17
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"

  logstash:
    build:
      context: .
      dockerfile: Dockerfile.Logstash
    image: cycloneproject/logging-logstash
    command: logstash --debug -f /run/secrets/logstash.conf
    secrets:
      - source: logstashconf
        target: logstash.conf
        mode: 0444
    expose:
      - "9400"
      - "9500"
      - "9600"
      - "9514"
    ports:
      - "9400:9400"
      - "9500:9500"
      - "9600:9600"
      - "9514:9514"

  filter:
    build:
      context: ./filter-proxy
    image: cycloneproject/logging-filter-proxy
    links:
      - elasticsearch
      - logstash
    ports:
      - "8080:8080"

