version: '2'

services:

    elasticsearch:
      image: elasticsearch:1.7
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./es-logging.yml:/usr/share/elasticsearch/config/logging.yml
        - ./es-template.json:/usr/share/elasticsearch/config/templates/es_template.json
        - ./es-data:/usr/share/elasticsearch/data
      expose:
        - "9200"
        - "9300"

    logstash:
      image: logstash:1.5
      volumes:
        - ./logstash.conf:/opt/logstash/logstash.conf
      #command: logstash --debug -f /opt/logstash/logstash.conf
      command: logstash -f /opt/logstash/logstash.conf
      expose:
        - "9400"
        - "9500"
        - "9600"
        - "9514"
      ports:
        - "9400:9400"
        - "9500:9500"
        - "9600:9600"
        - "9514:9514"

    filter:
      build: ./filter-proxy
      links:
        - elasticsearch
        - logstash
      ports:
        - "8080:8080"

